version: "3"
services:
  mongodb:
    image: "mongo:5.0"
    container_name: "shirpotrip-mongodb"
    #restart: always
    ports:
      - 27017:27017
  api:
    build: ./
    container_name: "shirpotrip-api"
    #restart: always
    ports:
      - 8080:8080
    links:
      - mongodb:app_db
    depends_on:
      - mongodb